### ISSUE TITLE
Error: emd: Signature size is limited to 100

### ISSUE THREAD

**Issue by icarocd** [mkusner/wmd#18]
During the wmd distance matrix computation, it occurs "emd: Signature size is limited to 100" several times. What should be done?

**Comment by icarocd** [comment]
The use of pre-trained word2vec based on google news provides 300-dimensional word vectors, but EMD algorithms does not seem to handle such amount. ?

**Comment by Itstudent87** [comment]
you have to edit one line in  "python-emd-master\emd.h" (for python) or "emd\emd.h" (for matlab )

find definitions and edit MAX_SIG_SIZE
`#define MAX_SIG_SIZE 100 `
